version: "3.8"

services:
  db:
    image: postgres:15
    container_name: crypto_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: crypto_data
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    image: smokepaus/crypto_backend:latest
    container_name: crypto_backend
    restart: always
    depends_on:
      - db
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DB: crypto_data
      POSTGRES_USER: postgres

  gui:
    image: smokepaus/crypto_gui:latest
    container_name: crypto_gui
    restart: "no"
    depends_on:
      - db
    environment:
      DISPLAY: $DISPLAY  # Needed for PyQt6 GUI

volumes:
  postgres_data:
