# Use a lightweight Python image
FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# Set environment variables WITHOUT password
ENV POSTGRES_HOST=db
ENV POSTGRES_PORT=5432
ENV POSTGRES_DB=crypto_data
ENV POSTGRES_USER=postgres

CMD ["python", "data_handler.py"]
