version: "3.8"

services:
  db:
    image: postgres:15
    container_name: crypto_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: crypto_data
      POSTGRES_PASSWORD: 7aGpc4Uj 
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: smokepaus/crypto_app:latest
    container_name: crypto_app
    restart: always
    depends_on:
      - db
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DB: crypto_data
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 7aGpc4Uj
      # BITGET_API_KEY: "bg_50fd7ac311bad69ae30f93c18f925786"
      # BITGET_API_SECRET: "daa4e88b6b6fb367ac184ed437228e0985ae6fc4b7d119c89b612fa78267e8a3"
      # BITGET_API_PASSPHRASE: "123456879"
      # For X11 forwarding: use host.docker.internal on Windows;
      # On Linux, you may also mount /tmp/.X11-unix.
      DISPLAY: host.docker.internal:0
      QT_DEBUG_PLUGINS: 1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix  # Useful on Linux; harmless on Windows
volumes:
  postgres_data:
